### PR TITLE
update README with new logo

### PR DESCRIPTION
**Pull request by iKristy**
Removes the old version of the README image and replaces it with one donning the new Netlify logo ✨

### CODE REVIEW

**Comment by ascorbic** [comment]
We should use [the new Angular logo too](https://angular.dev/press-kit)!

**Comment by ascorbic** [comment]
First time I can remember seeing brand guidelines that expressly tell you that you _can_ adapt the logo!

**Comment by Skn0tt** [comment]
oh, didn't see this. Thanks kristy! I had updated the logo over here already: https://github.com/netlify/netlify-plugin-angular-universal/pull/67/commits/a0a8dc756ae3f11c62e5fdc41ea20d954bc4e53a

**Comment by Skn0tt** [comment]
closing in favour of #67

**Pull request closed without merging**
